// ==========================================
// PDF Service — Report generation using PDFKit
// ==========================================

const PDFDocument = require('pdfkit');

/**
 * Generate NAAC/NBA report as PDF buffer.
 */
async function generateReportPDF(reportData) {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ margin: 50, size: 'A4' });
      const buffers = [];

      doc.on('data', (chunk) => buffers.push(chunk));
      doc.on('end', () => resolve(Buffer.concat(buffers)));

      // Title
      doc.fontSize(18).font('Helvetica-Bold')
        .text('PICT Smart CIE Evaluation Report', { align: 'center' });
      doc.moveDown(0.5);
      doc.fontSize(14).font('Helvetica')
        .text(`${reportData.reportType} Report`, { align: 'center' });
      doc.moveDown();

      // Metadata
      doc.fontSize(10).font('Helvetica');
      doc.text(`Subject: ${reportData.subjectName} (${reportData.subjectCode})`);
      doc.text(`Faculty: ${reportData.facultyName}`);
      doc.text(`Class: ${reportData.className}`);
      doc.text(`Academic Year: ${reportData.academicYear}`);
      doc.text(`Generated: ${new Date().toLocaleDateString()}`);
      doc.moveDown();
      doc.moveTo(50, doc.y).lineTo(545, doc.y).stroke();
      doc.moveDown();

      // Sections
      const sections = [
        { title: 'Activities Conducted', content: reportData.content.activitiesConducted },
        { title: 'Rubrics Used', content: reportData.content.rubrics },
        { title: 'Evaluation Method', content: reportData.content.evaluationMethod },
        { title: 'Score Distribution', content: reportData.content.scoreDistribution },
        { title: 'Observations', content: reportData.content.observations },
        { title: 'Weakness Analysis', content: reportData.content.weaknessAnalysis },
        { title: 'Improvement Actions', content: reportData.content.improvementActions },
        { title: 'Outcome Narrative', content: reportData.content.outcomeNarrative },
      ];

      for (const section of sections) {
        if (section.content) {
          doc.fontSize(12).font('Helvetica-Bold').text(section.title);
          doc.moveDown(0.3);
          doc.fontSize(10).font('Helvetica').text(section.content, { lineGap: 2 });
          doc.moveDown();
        }
      }

      // Footer
      doc.moveDown();
      doc.fontSize(8).font('Helvetica')
        .text('Generated by PICT Smart CIE Evaluation Platform', { align: 'center' });

      doc.end();
    } catch (err) {
      reject(err);
    }
  });
}

module.exports = { generateReportPDF };
